apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  namespace: flag-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      containers:
        - name: flag-service
          # Imagem ajustada para o padrão do repositório ECR criado no Terraform
          image: 191468900606.dkr.ecr.us-east-1.amazonaws.com/togglemaster-flag
          ports:
            - containerPort: 8002
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          env:
            # Host do RDS injetado pelo Terraform
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-db-config
                  key: DB_HOST_1
            # Senha do Infisical injetada pelo Terraform
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: togglemaster-db-secret
                  key: password_1
          envFrom:
            - configMapRef:
                name: flag-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: flag-service
  namespace: flag-namespace
spec:
  type: ClusterIP
  selector:
    app: flag-service
  ports:
    - port: 8002
      targetPort: 8002
---
# O Secret manual foi removido para usar o centralizado pelo Terraform/Infisical

apiVersion: v1
kind: ConfigMap
metadata:
  name: flag-service-config
  namespace: flag-namespace
data:
  PORT: "8002"
  AUTH_SERVICE_URL: "http://auth-service.auth-namespace.svc.cluster.local:8001"
  # Removida a DATABASE_URL fixa com senha exposta
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flag-service-ingress
  namespace: flag-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /flags/?(.*)
            pathType: Prefix
            backend:
              service:
                name: flag-service
                port:
                  number: 8002