apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: analytics-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: 191468900606.dkr.ecr.us-east-1.amazonaws.com/analytics-service
          ports:
            - containerPort: 8005
          resources:
            requests:
              cpu: "250m"      # Reserva 1/4 de um núcleo
              memory: "256Mi"  # Reserva 256MB de RAM
            limits:
              cpu: "500m"      # Pode usar até meio núcleo se precisar
              memory: "512Mi"  # Teto de 512MB para não travar o nó
          envFrom:
          - secretRef:
              name: analytics-service-secrets
          - configMapRef:
              name: analytics-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: analytics-namespace
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - port: 8005
      targetPort: 8005
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secrets
  namespace: analytics-namespace
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "ASIASZFDPSD7DRNQNHQR"
  AWS_SECRET_ACCESS_KEY: "A+chE8ZMqLvbQaNZ/NuviAS1ssdfBWXn9yGmacMB"
  AWS_SESSION_TOKEN: "IQoJb3JpZ2luX2VjEDIaCXVzLXdlc3QtMiJGMEQCIFeYgUZhSaHe9cwAPIKXoQS4KvwfM3E1+Xhi8BrPBQwRAiByEdRll1YZoAORLLYFCLB+Msuwl8xXeY21XEW/TlXsUSqxAgj7//////////8BEAAaDDE5MTQ2ODkwMDYwNiIMrrKQw9X/CcC2d6GAKoUCU0iyboibPLZetJd9qvVMtxSLBh6KyCRh3+dIP/CZ6y6+c7G9jTrdnhcEjnbLUIrSZVb7G4nWRo/y6Nv+kqfxZZ41WZoJrUCNRJwbT+TBD1rmVvQGgS7Bgjd0CtTDXujkh2Z/6In2dM22zwmc+r1Zo+ek05UiQewfJEWxBBBhgaApFphSmoZaOUBTPw4LIwE//HWclyi6VlXeOLXUEfIkEccfnlCe1/mSrxXI9CRU2FntMkwuMllKJiSeETdQqp9UGhx249r2lFfq+fjAT6xMC0eIPqKRAIbMuiIbdpoS8HjXalGx9NyLUK9I/xbRf//Ons629PitRBnVdGOLSfd6hvMcD51XMOT8580GOp4BvE43HjvZLKxYtk+t+0CRlw5PirhCM5WUvuLotVkYbnAycj3AU+usS312AZcw4oA4tTTuPyGYiPKOv2TxCp1vYfrYcWby9JWEseEpWhBkhxH3nR5touO+TeVek2OcvyN6koFJb1d0AIk9MIVeuTWlMUMssul4sOvC7DzzR8l/RirbqZ4xWIeGzL2NTaV/7DHQy8VpfkmQ4Enb0i/MHXM="
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: analytics-namespace
data:
  ANALYTICS_PORT: "8005"
  AWS_REGION: "us-east-1"
  REDIS_URL: "rediss://clustercfg.togglemaster-redis-prod.n7s9nu.use1.cache.amazonaws.com:6379"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/191468900606/togglemaster-sqs-prod"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
