apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: analytics-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: <ECR_REPO>/analytics-service:latest
          ports:
            - containerPort: <>
          envFrom:
            - secretRef:
                name: analytics-service-secrets
            - configMapRef:
                name: analytics-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: analytics-namespace
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - port: <>
      targetPort: <>
---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secrets
  namespace: analytics-namespace
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "ASIAW3MEBYNOG4QTX4RU"
  AWS_SECRET_ACCESS_KEY: "EDFvZYHiPBelwntXpuBwhOeAYJT8k722jVM8EYs1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: analytics-namespace
data:
  ANALYTICS_PORT: "8005"
  AWS_REGION: "us-east-1"
  REDIS_URL: "redis-evaluation.lohxif.cfg.use1.cache.amazonaws.com:11211"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/471112729436/sqs-service"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
