apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: evaluation-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: 191468900606.dkr.ecr.us-east-1.amazonaws.com/evaluation-service
          ports:
            - containerPort: 8004
          envFrom:
            - secretRef:
                name: evaluation-service-secrets
            - configMapRef:
                name: evaluation-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: evaluation-namespace
spec:
  type: ClusterIP
  selector:
    app: evaluation-service
  ports:
    - port: 8004
      targetPort: 8004
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-secrets
  namespace: evaluation-namespace
type: Opaque
stringData:
  SERVICE_API_KEY: "tm_key_4dc494b3ef361406512eee8ca195f7b6fcf912c64091ab06e5fbac4fb0bbf1a9"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
  namespace: evaluation-namespace
data:
  EVALUATION_PORT: "8004"
  AUTH_SERVICE_URL: "http://auth-service.auth-namespace.svc.cluster.local:8001"
  FLAG_SERVICE_URL: "http://flag-service.flag-namespace.svc.cluster.local:8002"
  TARGETING_SERVICE_URL: "http://targeting-service.targeting-namespace.svc.cluster.local:8003"