apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  namespace: flag-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      containers:
        - name: flag-service
          image: 191468900606.dkr.ecr.us-east-1.amazonaws.com/flag-repo
          ports:
            - containerPort: 8002
          envFrom:
            - secretRef:
                name: flag-service-secrets
            - configMapRef:
                name: flag-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: flag-service
  namespace: flag-namespace
spec:
  type: ClusterIP
  selector:
    app: flag-service
  ports:
    - port: 8002
      targetPort: 8002
---
apiVersion: v1
kind: Secret
metadata:
  name: flag-service-secrets
  namespace: flag-namespace
type: Opaque
data:
  DB_PASSWORD: UjVFR10xJEJIKHY5JGhZazlHWyk6WFBkPkNwPw==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flag-service-config
  namespace: flag-namespace
data:
  DATABASE_URL: "postgres://postgres:R5EG%5D1%24BH%28v9%24hYk9G%5B%29%3AXPd%3ECp%3F@flag-postgres.czemuyq424d3.us-east-1.rds.amazonaws.com:5432/flagdb"
  AUTH_SERVICE_URL:  "http://auth-service.auth-namespace.svc.cluster.local:8001"
  PORT: "8002"
  SERVICE_URL: "http://flag-service:8002"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flag-service-ingress
  namespace: flag-namespace
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /flags
            pathType: Prefix
            backend:
              service:
                name: flag-service
                port:
                  number: 8002