apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: targeting-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      containers:
        - name: targeting-service
          image: 471112729436.dkr.ecr.us-east-1.amazonaws.com/targeting-service
          ports:
            - containerPort: 8003
          envFrom:
            - secretRef:
                name: targeting-service-secrets
            - configMapRef:
                name: targeting-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: targeting-service
  namespace: targeting-namespace
spec:
  type: ClusterIP
  selector:
    app: targeting-service
  ports:
    - port: 8003
      targetPort: 8003
---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secrets
  namespace: targeting-namespace
type: Opaque
data:
  DB_PASSWORD: LWVFLUpNNCpQQWxbKmZ2MGx3NTRRIU9OPE1mKg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-service-config
  namespace: targeting-namespace
data:
  DATABASE_URL: "postgres://postgres:-eE-JM4%2APAl%5B%2Afv0lw54Q%21ON%3CMf%2A@targeting-postgres.czemuyq424d3.us-east-1.rds.amazonaws.com:5432/targetingdb"
  AUTH_SERVICE_URL:  "http://auth-service.auth-namespace.svc.cluster.local:8001"
  PORT: "8003"
  SERVICE_URL: "http://targeting-service:8003"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: targeting-service-ingress
  namespace: targeting-namespace
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /targeting
            pathType: Prefix
            backend:
              service:
                name: targeting-service
                port:
                  number: 8003