apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: targeting-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      containers:
        - name: targeting-service
          image: 191468900606.dkr.ecr.us-east-1.amazonaws.com/targeting-service
          ports:
            - containerPort: 8003
          envFrom:
            - secretRef:
                name: targeting-service-secrets
            - configMapRef:
                name: targeting-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: targeting-service
  namespace: targeting-namespace
spec:
  type: ClusterIP
  selector:
    app: targeting-service
  ports:
    - port: 8003
      targetPort: 8003
---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-service-secrets
  namespace: targeting-namespace
type: Opaque
data:
  DB_PASSWORD: Zm13dldvOmV8PFhTRTdGTFJzeCp3b1tMR3cqeg==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: targeting-service-config
  namespace: targeting-namespace
data:
  DATABASE_URL: "postgres://postgres:fmwvWo%3Ae%7C%3CXSE7FLRsx%2Awo%5BLGw%2Az@potsgres-targeting.cpuaso8oc4w8.us-east-1.rds.amazonaws.com:5432/targetingdb"
  AUTH_SERVICE_URL:  "http://auth-service.auth-namespace.svc.cluster.local:8001"
  FLAG_SERVICE_URL: "http://flag-service.flag-namespace.svc.cluster.local:8002"
  PORT: "8003"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: targeting-service-ingress
  namespace: targeting-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /targeting(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: targeting-service
                port:
                  number: 8003