apiVersion: batch/v1
kind: Job
metadata:
  name: auth-postgres-init
  namespace: auth-namespace
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: auth-postgres-init-sql
        image: postgres:latest
        command: ["psql"]
        args: 
          - "-h"
          - "$(DB_HOST)" 
          - "-U"
          - "masteruser"
          - "-d"
          - "togglemaster"
          - "-f"
          - "/mnt/init.sql"
        env:
          # Host dinâmico vindo do RDS de Auth (Índice 0)
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: togglemaster-db-config
                key: DB_HOST_0
          # Senha segura vinda do Infisical (Índice 0)
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: togglemaster-db-secret
                key: DB_PASS_0
        volumeMounts:
        - name: init-sql
          mountPath: /mnt
      volumes:
      - name: init-sql
        config_map:
          name: auth-postgres-init-configmap
---
# Secret manual removido para usar a integração com o Terraform/Infisical

apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-postgres-init-configmap
  namespace: auth-namespace
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS api_keys (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        key_hash VARCHAR(64) NOT NULL UNIQUE,
        is_active BOOLEAN DEFAULT true,
        created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );