apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: auth-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: 191468900606.dkr.ecr.us-east-1.amazonaws.com/auth-service
          ports:
            - containerPort: 8001
          env:
            # Pegando o host do ConfigMap gerado pelo Terraform
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-db-config
                  key: DB_HOST_0
            # Pegando a senha do Secret gerado pelo Terraform (Infisical)
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: togglemaster-db-secret
                  key: password_0
          # Se sua aplicação ainda precisar do ConfigMap/Secret antigo para outras chaves:
          envFrom:
            - secretRef:
                name: auth-service-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service    
  namespace: auth-namespace
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 8001
      targetPort: 8001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-service-ingress
  namespace: auth-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /auth(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: auth-service
                port:
                  number: 8001