apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: analytics-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: 191468900606.dkr.ecr.us-east-1.amazonaws.com/analytics-service
          ports:
            - containerPort: 8005
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            # Pega o Endpoint do Redis gerado pelo Terraform
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: togglemaster-db-config
                  key: REDIS_ENDPOINT
            # As chaves AWS não devem ficar aqui. 
            # No LabRole da Academy, o EKS já tem permissão para SQS/Dynamo.
            - name: AWS_REGION
              value: "us-east-1"
            - name: AWS_DYNAMODB_TABLE
              value: "ToggleMasterAnalytics"
          # Mantemos o envFrom apenas para configurações menores
          envFrom:
            - configMapRef:
                name: analytics-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: analytics-namespace
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - port: 8005
      targetPort: 8005
---
# Removi o Secret manual (AWS_ACCESS_KEY) pois é inseguro e expira.
# Removi a REDIS_URL manual do ConfigMap pois agora vem do Terraform.

apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: analytics-namespace
data:
  ANALYTICS_PORT: "8005"
  # Coloque aqui apenas URLs fixas ou nomes de filas se não vierem do TF
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/191468900606/togglemaster-queue"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: analytics-service-ingress
  namespace: analytics-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /analytics(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: analytics-service
                port:
                  number: 8005